export type {
  ActionConfig,
  ActionType,
  AdvancementCondition,
  BranchStepV2,
  CompoundCondition,
  ConditionConfig,
  SimpleCondition,
  SimpleConditionType,
  StandardStepV2,
  TriggerType,
  VariableDataType,
  VariableSource,
  VariableType,
  WorkflowAction,
  WorkflowDefinitionV2,
  WorkflowPhase,
  WorkflowStatus,
  WorkflowStepV2,
  WorkflowTrigger,
  WorkflowVariable,
  WorkflowVariableField,
} from "@/lib/workflow-builder-v2/types"

export {
  isBranchStep,
  isCompoundCondition,
  isSimpleCondition,
  isStandardStep,
} from "@/lib/workflow-builder-v2/types"
